@echo off
echo Starting Basketball League Backend...
start "Backend" cmd /k "cd /d C:\Users\romsk\IdeaProjects\basketball-league && "C:\Program Files\Java\jdk-22\bin\java" -jar target\basketball-league-0.0.1-SNAPSHOT.jar"

echo Starting Basketball League Frontend...
start "Frontend" cmd /k "cd /d C:\Users\romsk\Coding\Web Development\NextJS\basketball-league && npm run dev"
